command:
  name: Command
  description: Execute various linkplay-specific commands on the player.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the player against which the command wil be execuded.
      example: media_player.sound_room1
      required: true
      selector:
        entity:
          integration: linkplay
    command:
      name: Command
      description: 'To set the names for WriteDeviceNameToUnit and SetApSSIDName please switch to YAML mode and enter the name there.'
      example: Update
      required: true
      selector:
        select:
          options:
            - Rescan
            - reboot
    notify:
      name: Notification
      description: Displays the result of the command as a persistent notification in Lovelace UI (optional, defaults to True). Set to False during automations to avoid seeing these.
      example: false
      required: false
      default: true
      selector:
        boolean: